from .turism import Turism

pentagon = Turism("Pentagon Guided Tour", sku='T01')
white_house = Turism("White House Guided Tour", sku='T02')
smithsonians = Turism("Smithsonian Museum", sku='T03')
melbourne_zoo = Turism("Melbourne Zoo", sku='T04')
icebar = Turism("Melbourne Icebar", sku='T05')
great_ocean_road = Turism("Great Ocean Road Guided Tour", sku='T06')
great_wall = Turism("Great Wall", sku='T07')
forbidden_city = Turism("Forbidden City", sku='T08')
tiananmen = Turism("Tiananmen Square", sku='T09')
blue_city = Turism("Chauen Blue City", sku='T10')
desert_tour = Turism("Desert Tour", sku='T11')
la_medina_tour = Turism("La Medina Tour", sku='T12')
sky_costanera = Turism("Sky Costanera", sku='T13')
santa_rita_winery = Turism("Santa Rita Winery tour", sku='T14')
big_bus_tour = Turism("Big Bus Tour around Santiago", sku='T15')
eiffel_tower = Turism("Eiffel Tower", sku='T16')
louvre = Turism("Louvre Museum", sku='T17')
notre_dame = Turism("Notre Dame Catedral", sku='T18')
